# =================================================================================================
# apply_qc_thresholds()
# -------------------------------------------------------------------------------------------------
# Purpose:
#   Apply the QC thresholds generated by qc_plots_by_sample() to a Seurat object and remove:
#       (1) Cells failing any per-metric min/max threshold, and/or
#       (2) Cells belonging to exact "low-quality" groups (optional).
#
# What the function does:
#   • Merges per-sample QC thresholds (min/max per metric) into the Seurat metadata.
#   • For each cell:
#         - Compares metric values against sample-specific min/max cutoffs.
#         - Records which metrics failed (if any).
#   • Optionally removes entire low-quality groups (exact category matches in lowqc_col).
#   • Produces:
#         - A filtered Seurat object.
#         - A summary of kept/removed cell counts.
#         - A breakdown of failure reasons.
#         - A metadata column `QC_fail_reason` labeling the reason each cell was removed.
#
# Inputs:
#   seurat_obj      : A Seurat object containing QC metrics.
#   thresholds_df   : The $thresholds output from qc_plots_by_sample().
#   sample_col      : Column used to match thresholds to cells (same as used for thresholding).
#   lowqc_col       : Metadata column whose values identify groups to be forcibly removed.
#   lowqc_groups    : Character vector of exact group names to remove (optional).
#   ignore_case     : If TRUE, matches lowqc_groups case-insensitively.
#
# Internal processing steps:
#   1. Keep only threshold rows for metrics actually present in metadata.
#   2. Spread thresholds into wide format: one min__metric and max__metric per sample.
#   3. Join thresholds onto metadata by sample.
#   4. Evaluate each metric for each cell:
#         fail = value < min_thr OR value > max_thr.
#   5. Compile metric-wise failure labels and combine into QC_fail_reason.
#   6. Apply optional exact-match filtering for low-QC groups.
#   7. Subset the Seurat object to retained cells.
#
# Outputs (returned as a list):
#   $obj               : Filtered Seurat object.
#   $summary           : A tibble with total/kept/removed cell counts.
#   $removed_breakdown : A frequency table of failure reasons (e.g., "nCount_RNA", "percent.mt", etc.).
#
# Dependencies:
#   dplyr, tidyr, tibble, Seurat
#
# Notes:
#   • This function does not recompute thresholds; it strictly applies pre-computed ones.
#   • lowqc_groups is for *exact* category removal, unlike threshold-based filtering.
#   • QC_fail_reason is written to the object even for kept cells (empty string).
# =================================================================================================


# ---- Apply QC thresholds & drop exact low-QC groups -------------------------
# deps: dplyr, tidyr, tibble, Seurat
apply_qc_thresholds <- function(
    seurat_obj,
    thresholds_df,                   # res$thresholds from qc_plots_by_sample()
    sample_col   = "Sample",       # column used to compute thresholds
    lowqc_col    = "CellType_AllCells",
    lowqc_groups = NULL,             # <-- character vector of exact group names to remove
    ignore_case  = TRUE              # match lowqc_groups case-insensitively if TRUE
){
  stopifnot(sample_col %in% colnames(seurat_obj@meta.data))
  meta <- seurat_obj@meta.data %>% tibble::rownames_to_column("cell")
  
  # Keep only thresholds whose metrics exist in metadata
  metrics <- intersect(unique(thresholds_df$metric), colnames(meta))
  th <- thresholds_df %>% dplyr::filter(metric %in% metrics)
  
  # Per-batch min/max tables
  th_min <- th %>%
    dplyr::select(sample, metric, min_thr) %>%
    tidyr::pivot_wider(names_from = metric, values_from = min_thr, names_prefix = "min__")
  th_max <- th %>%
    dplyr::select(sample, metric, max_thr) %>%
    tidyr::pivot_wider(names_from = metric, values_from = max_thr, names_prefix = "max__")
  th_wide <- dplyr::full_join(th_min, th_max, by = "sample")
  
  # Join thresholds by sample/batch to each cell
  meta2 <- meta %>%
    dplyr::left_join(th_wide, by = dplyr::join_by(!!as.name(sample_col) == sample))
  
  # Build keep mask + failure reasons (per-metric)
  keep <- rep(TRUE, nrow(meta2))
  if (length(metrics)) {
    fail_mat <- matrix(FALSE, nrow(meta2), length(metrics),
                       dimnames = list(meta2$cell, metrics))
    for (m in metrics) {
      v    <- meta2[[m]]
      vmin <- meta2[[paste0("min__", m)]]
      vmax <- meta2[[paste0("max__", m)]]
      fail <- (is.finite(vmin) & v < vmin) | (is.finite(vmax) & v > vmax)
      fail_mat[, m] <- fail
      keep <- keep & !fail
    }
    reasons_metric <- apply(fail_mat, 1, function(x) paste(colnames(fail_mat)[x], collapse = ";"))
    reasons_metric[reasons_metric == ""] <- NA_character_
  } else {
    reasons_metric <- rep(NA_character_, nrow(meta2))
  }
  
  # Drop exact low-QC groups if requested
  lowqc_fail <- rep(FALSE, nrow(meta2))
  if (!is.null(lowqc_groups) && length(lowqc_groups) && lowqc_col %in% colnames(meta2)) {
    col_vals <- meta2[[lowqc_col]]
    if (ignore_case) {
      lowqc_fail <- tolower(col_vals) %in% tolower(lowqc_groups)
    } else {
      lowqc_fail <- col_vals %in% lowqc_groups
    }
    keep <- keep & !lowqc_fail
  }
  
  # Compile reasons
  reasons <- reasons_metric
  if (any(lowqc_fail)) {
    tag <- if (length(lowqc_groups) == 1) paste0("low_QC_group=", lowqc_groups) else "low_QC_group"
    reasons <- ifelse(
      lowqc_fail,
      ifelse(is.na(reasons), tag, paste0(reasons, ";", tag)),
      reasons
    )
  }
  reasons[is.na(reasons)] <- ""
  
  # Attach reasons back to object and subset
  seurat_obj$QC_fail_reason <- reasons[match(Cells(seurat_obj), meta2$cell)]
  cells_keep <- meta2$cell[keep]
  seurat_filtered <- subset(seurat_obj, cells = cells_keep)
  
  summary_tbl <- tibble::tibble(
    total_cells   = nrow(meta2),
    kept_cells    = length(cells_keep),
    removed_cells = nrow(meta2) - length(cells_keep)
  )
  
  list(
    obj = seurat_filtered,
    summary = summary_tbl,
    removed_breakdown = sort(table(ifelse(reasons == "", "kept", reasons)), decreasing = TRUE)
  )
}
